Actividades/Ruby on Rails/CRUD_USUARIOS/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


root to: "usuarios#new"

get 'usuarios/new'

post 'usuarios/recibir_datos'

end

Actividades/Ruby on Rails/CRUD_USUARIOS/app/models/user.rb
class User < ApplicationRecord
	
end

Actividades/Ruby on Rails/CRUD_USUARIOS/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController


def new
  end

def recibir_datos
	user_params = params.require(:user).permit(
		:ced,
		:name,
		:lastname,
		:email,
		:tel

		)
	user = User.new(user_params)
	user.save()
end 

end

Actividades/Ruby on Rails/CRUD_USUARIOS/app/helpers/usuario_controller_helper.rb
module UsuarioControllerHelper
end

Actividades/Ruby on Rails/CRUD_USUARIOS/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Actividades/Ruby on Rails/CRUD_USUARIOS/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUDUsuarios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Actividades/Ruby on Rails/CRUD_USUARIOS/app/views/usuarios/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>CRUD USUARIOS</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

</head>
<body>

<div class="container-fluid">
	
	<div class="row">
		<div class="col-12 text-center">
			
		</div>
		

	</div>
	

	<div class="row">
		
	<div class="col-4"></div>

		<div class="col-4">
			


			<div class="card">
  <h5 class="card-header text-center">CRUD DE USUARIOS</h5>
  <div class="card-body">
   
			<form method="POST" action="<%= usuarios_recibir_datos_path %>">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
 

<div class="form-group">
    <label for="ced">Cédula</label>
    <input type="text" class="form-control" id="ced" name="user[ced]"  placeholder="Escriba su Cédula">
   
  </div>
  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control" id="nombre" name="user[name]"  placeholder="Escriba su Nombre">
   
  </div>

  <div class="form-group">
    <label for="ape">Apellidos</label>
    <input type="text" class="form-control" id="ape" name="user[lastname]"   placeholder="Escriba sus Apellidos">
   
  </div>

  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" id="email" name="user[email]"  placeholder="Escriba su Email">
   
  </div>
  <div class="form-group">
    <label for="tel">Teléfono</label>
    <input type="text" class="form-control" id="tel" name="user[tel]"  placeholder="Escriba su Teléfono">
   
  </div>
  
  <button type="submit" class="btn btn-primary">Guardar</button>
</form>
 </div>
</div>
		</div>
		<div class="col-4">
			

		</div>
	</div>

</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>


</body>
</html>