Actividades/Ruby on Rails/blog/config/routes.rb
Rails.application.routes.draw do

  resources :elementos
root to: "welcome#index"
  get 'welcome/index'
  get 'welcome/mivista'
   get 'welcome/mivistajson'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Actividades/Ruby on Rails/blog/app/models/elemento.rb
class Elemento < ApplicationRecord
end

Actividades/Ruby on Rails/blog/app/controllers/elementos_controller.rb
class ElementosController < ApplicationController
  before_action :set_elemento, only: [:show, :edit, :update, :destroy]

  # GET /elementos
  # GET /elementos.json
  def index
    @elementos = Elemento.all
  end

  # GET /elementos/1
  # GET /elementos/1.json
  def show
  end

  # GET /elementos/new
  def new
    @elemento = Elemento.new
  end

  # GET /elementos/1/edit
  def edit
  end

  # POST /elementos
  # POST /elementos.json
  def create
    @elemento = Elemento.new(elemento_params)

    respond_to do |format|
      if @elemento.save
        format.html { redirect_to @elemento, notice: 'Elemento was successfully created.' }
        format.json { render :show, status: :created, location: @elemento }
      else
        format.html { render :new }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elementos/1
  # PATCH/PUT /elementos/1.json
  def update
    respond_to do |format|
      if @elemento.update(elemento_params)
        format.html { redirect_to @elemento, notice: 'Elemento was successfully updated.' }
        format.json { render :show, status: :ok, location: @elemento }
      else
        format.html { render :edit }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elementos/1
  # DELETE /elementos/1.json
  def destroy
    @elemento.destroy
    respond_to do |format|
      format.html { redirect_to elementos_url, notice: 'Elemento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elemento
      @elemento = Elemento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elemento_params
      params.require(:elemento).permit(:game, :score)
    end
end

Actividades/Ruby on Rails/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def mivista
  end


  def mivistajson

render json: {
	data: 'algun contenido'
}



  end
end

Actividades/Ruby on Rails/blog/app/helpers/elementos_helper.rb
module ElementosHelper
end

Actividades/Ruby on Rails/blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Actividades/Ruby on Rails/blog/app/views/elementos/_form.html.erb
<%= form_for(elemento) do |f| %>
  <% if elemento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elemento.errors.count, "error") %> prohibited this elemento from being saved:</h2>

      <ul>
      <% elemento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %>
    <%= f.text_field :game %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Actividades/Ruby on Rails/blog/app/views/elementos/edit.html.erb
<h1>Editing Elemento</h1>

<%= render 'form', elemento: @elemento %>

<%= link_to 'Show', @elemento %> |
<%= link_to 'Back', elementos_path %>

Actividades/Ruby on Rails/blog/app/views/elementos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elementos</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elementos.each do |elemento| %>
      <tr>
        <td><%= elemento.game %></td>
        <td><%= elemento.score %></td>
        <td><%= link_to 'Show', elemento %></td>
        <td><%= link_to 'Edit', edit_elemento_path(elemento) %></td>
        <td><%= link_to 'Destroy', elemento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elemento', new_elemento_path %>

Actividades/Ruby on Rails/blog/app/views/elementos/new.html.erb
<h1>New Elemento</h1>

<%= render 'form', elemento: @elemento %>

<%= link_to 'Back', elementos_path %>

Actividades/Ruby on Rails/blog/app/views/elementos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @elemento.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @elemento.score %>
</p>

<%= link_to 'Edit', edit_elemento_path(@elemento) %> |
<%= link_to 'Back', elementos_path %>

Actividades/Ruby on Rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Actividades/Ruby on Rails/blog/app/views/welcome/index.html.erb
<div class="row">

	<h1 style="text-align: center">Primera Clase Ruby On Rails</h1>

</div>

Actividades/Ruby on Rails/blog/app/views/welcome/mivista.html.erb
<h1>Mi vista </h1>

Actividades/Ruby on Rails/blog/app/views/welcome/mivistajson.html.erb
mivistajson.html.erb